import type { PlacementCategory } from '../../types';

export interface PiercingHotspot {
  id: string;
  name: string;
  basePrice: number;
  category: PlacementCategory;
  /** Allowed "Initial Jewelry Material" price tiers shown on the booking modal.
   *  When omitted, all tiers (0/50/150/200) are offered. */
  jewelryPrices?: number[];
  x: number; // percentage (0 - 100) or SVG coords
  y: number; // percentage (0 - 100) or SVG coords
  healingInfo: string;
  painLevel: string;
  description: string;
  anatomyDependent?: boolean;
  anatomyNote?: string;
}

export const EAR_HOTSPOTS: PiercingHotspot[] = [
  {
    id: 'lobe',
    name: 'Lobe',
    basePrice: 300,
    category: 'EAR',
    x: 52,
    y: 86,
    healingInfo: '6–8 weeks',
    painLevel: '1/10',
    description: 'The classic earlobe piercing. Fast healing and highly versatile for studs and hoops.',
  },
  {
    id: 'auricle',
    name: 'Auricle',
    basePrice: 350,
    category: 'EAR',
    x: 77,
    y: 63,
    healingInfo: '3–6 months',
    painLevel: '3/10',
    description: 'Placed along the outer middle ear rim between the lobe and upper helix.',
  },
  {
    id: 'helix',
    name: 'Helix',
    basePrice: 400,
    category: 'EAR',
    x: 68,
    y: 20,
    healingInfo: '6–9 months',
    painLevel: '3/10',
    description: 'Upper outer cartilage rim. Beautiful for delicate studs, hoops, or cuffs.',
  },
  {
    id: 'forward_helix',
    name: 'Forward Helix',
    basePrice: 400,
    category: 'EAR',
    x: 32,
    y: 26,
    healingInfo: '6–9 months',
    painLevel: '4/10',
    description: 'Front rim of the ear cartilage directly above the tragus facing the face.',
  },
  {
    id: 'flat',
    name: 'Flat',
    basePrice: 400,
    category: 'EAR',
    x: 52,
    y: 24,
    healingInfo: '6–9 months',
    painLevel: '4/10',
    description: 'Flat area of cartilage below the upper rim, ideal for statement decorative studs.',
  },
  {
    id: 'conch',
    name: 'Conch',
    basePrice: 400,
    category: 'EAR',
    x: 56,
    y: 50,
    healingInfo: '6–9 months',
    painLevel: '4/10',
    description: 'Inner cup/bowl of the ear cartilage. Can be styled with a stud or a hugging hoop once healed.',
  },
  {
    id: 'tragus',
    name: 'Tragus',
    basePrice: 500,
    category: 'EAR',
    x: 29,
    y: 52,
    healingInfo: '6–9 months',
    painLevel: '4/10',
    description: 'Small rounded flap of cartilage right in front of the ear canal.',
  },
  {
    id: 'anti_tragus',
    name: 'Anti Tragus',
    basePrice: 500,
    category: 'EAR',
    x: 46,
    y: 72,
    healingInfo: '6–12 months',
    painLevel: '5/10',
    description: 'The small ridge of cartilage directly opposite the tragus, just above the lobe.',
  },
  {
    id: 'rook',
    name: 'Rook',
    basePrice: 450,
    category: 'EAR',
    // Rook: no rhinestone option; only the 150 titanium tier is available.
    jewelryPrices: [150],
    x: 40,
    y: 35,
    healingInfo: '6–12 months',
    painLevel: '5/10',
    description: 'Upper inner cartilage ridge above the daith. Styled with a curved barbell or small clicker.',
    anatomyDependent: true,
    anatomyNote: 'Requires a pronounced cartilage shelf above the daith to securely seat jewelry.',
  },
  {
    id: 'daith',
    name: 'Daith',
    basePrice: 450,
    category: 'EAR',
    x: 42,
    y: 46,
    healingInfo: '6–12 months',
    painLevel: '5/10',
    description: 'Deep innermost fold of cartilage right above the ear canal. Gorgeous with ornate heart rings.',
    anatomyDependent: true,
    anatomyNote: 'Requires a well-defined innermost cartilage fold (crus of helix) with adequate depth.',
  },
  {
    id: 'snug',
    name: 'Snug',
    basePrice: 500,
    category: 'EAR',
    x: 63,
    y: 56,
    healingInfo: '6–12 months',
    painLevel: '6/10',
    description: 'Horizontal cartilage ridge along the antihelix between the inner and outer ear.',
    anatomyDependent: true,
    anatomyNote: 'Requires a sufficiently raised antihelix ridge for safe through-and-through placement.',
  },
  {
    id: 'industrial',
    name: 'Industrial',
    basePrice: 700,
    category: 'EAR',
    x: 48,
    y: 14,
    healingInfo: '9–12 months',
    painLevel: '6/10',
    description: 'Double piercing connected by a single straight barbell across upper cartilage.',
    anatomyDependent: true,
    anatomyNote: 'Strictly anatomy dependent: Requires a pronounced outer helix curl and a flat scapha. Bar must not press on middle ear flat.',
  },
];

export const FACE_HOTSPOTS: PiercingHotspot[] = [
  {
    id: 'nostril',
    name: 'Nostril',
    basePrice: 400,
    category: 'FACE',
    x: 42,
    y: 44,
    healingInfo: '4–6 months',
    painLevel: '3/10',
    description: 'Piercing through either side of the nasal flare. Worn with studs, flatbacks, or hoops.',
  },
  {
    id: 'septum',
    name: 'Septum',
    basePrice: 450,
    category: 'FACE',
    x: 50,
    y: 48,
    healingInfo: '2–3 months',
    painLevel: '3/10',
    description: 'Through the "sweet spot" soft tissue inside the nose tip. Fast healing and easy to hide when needed.',
  },
  {
    id: 'eyebrow',
    name: 'Eyebrow',
    basePrice: 450,
    category: 'FACE',
    x: 35,
    y: 20,
    healingInfo: '3–4 months',
    painLevel: '3/10',
    description: 'Vertical surface piercing through the brow ridge, typically on the outer third.',
  },
  {
    id: 'medusa',
    name: 'Medusa',
    basePrice: 350,
    category: 'ORAL',
    x: 50,
    y: 62,
    healingInfo: '2–3 months',
    painLevel: '4/10',
    description: 'Also called the Philtrum piercing. Centered directly above the Cupid’s bow of the upper lip.',
  },
  {
    id: 'labret',
    name: 'Labret',
    basePrice: 350,
    category: 'ORAL',
    x: 50,
    y: 74,
    healingInfo: '2–3 months',
    painLevel: '4/10',
    description: 'Centered below the lower lip. A timeless piercing worn with a flatback labret stud or ring.',
  },
  {
    id: 'monroe',
    name: 'Monroe',
    basePrice: 350,
    category: 'ORAL',
    x: 38,
    y: 64,
    healingInfo: '2–3 months',
    painLevel: '4/10',
    description: 'Off-center upper lip placement resembling a beauty mark.',
  },
  {
    id: 'smiley',
    name: 'Smiley',
    basePrice: 400,
    category: 'ORAL',
    x: 50,
    y: 57,
    healingInfo: '4–8 weeks',
    painLevel: '2/10',
    description: 'Thin web of tissue (frenulum) inside upper gum, visible when smiling.',
  },
  {
    id: 'tongue',
    name: 'Tongue',
    basePrice: 500,
    category: 'ORAL',
    x: 50,
    y: 67,
    healingInfo: '4–6 weeks',
    painLevel: '3/10',
    description: 'Through the center of the tongue muscle. Surprisingly quick healing with proper oral hygiene.',
  },
  {
    id: 'dimple',
    name: 'Dimple',
    basePrice: 500,
    category: 'FACE',
    x: 28,
    y: 66,
    healingInfo: '6–12 months',
    painLevel: '6/10',
    description: 'Cheek piercing creating artificial or accentuating natural dimples.',
    anatomyDependent: true,
    anatomyNote: 'Requires careful anatomy mapping to safely navigate facial nerves and salivary parotid ducts.',
  },
];

export const BODY_HOTSPOTS: PiercingHotspot[] = [
  {
    id: 'navel',
    name: 'Navel',
    basePrice: 500,
    category: 'BODY',
    // Navel jewelry is intentionally free-only (stainless studs included).
    jewelryPrices: [0],
    x: 50,
    y: 48,
    healingInfo: '6–12 months',
    painLevel: '4/10',
    description: 'Standard upper rim of the belly button. Styled with curved banana barbells and charms.',
    anatomyDependent: true,
    anatomyNote: 'Requires a distinct upper lip and enough hollow depth when sitting and standing. Not all anatomies are suitable; consultation will evaluate suitability.',
  },
  {
    id: 'floating_navel',
    name: 'Floating Navel',
    basePrice: 550,
    category: 'BODY',
    // Floating navel jewelry is the +200 tier only (not included in base).
    jewelryPrices: [200],
    x: 50,
    y: 56,
    healingInfo: '6–12 months',
    painLevel: '4/10',
    description: 'Specialized placement for collapsed or deep navel anatomy where a standard lower ball would press.',
    anatomyDependent: true,
    anatomyNote: 'Specifically tailored for clients whose navels collapse or fold when seated, preventing rejection.',
  },
  {
    id: 'nipple_single',
    name: 'Nipple (single)',
    basePrice: 400,
    category: 'BODY',
    x: 32,
    y: 28,
    healingInfo: '9–12 months',
    painLevel: '6/10',
    description: 'Horizontal piercing through the base of the nipple. Single placement.',
  },
];
